'use strict';

const FIRST_NAMES = [ "Adalbert",
                "Adolf",
                "Alfonz",
                "Amadeusz",
                "Anakin",
                "Andzseló",
                "Bagamér",
                "Balabán",
                "Balambér",
                "Baltazár",
                "Bartos",
                "Benediktusz",
                "Béni",
                "Benő",
                "Benvenútó",
                "Berengár",
                "Bojtorján",
                "Brájen",
                "Brendon",
                "Ciceró",
                "Dagobert",
                "Dáriusz",
                "Dzsúlió",
                "Ezékiel",
                "Ézsaiás",
                "Frodó",
                "Gandalf",
                "Gilgames",
                "Gothárd",
                "Günter",
                "Habib",
                "Hannibál",
                "Horáciusz",
                "Jákob",
                "Jónás",
                "József",
                "Koppány",
                "Lúciusz",
                "Malakiás",
                "Ödön",
                "Szókratész",
                "Tóbiás",
                "Ubul",
                "Uriel",
                "Vérbulcsú",
                "Zakariás"
];

const NICKNAMES = [ ",az agilis",
                    ",a tigrincs",
                    ",a veszett",
                    ",a huncut",
                    ",az őrült",
                    ",a kegyetlen",
                    ",az átkozott",
                    ",a gyűlölt",
                    ",a rettegett",
                    ",a csicska",
                    ",a murloc",
                    ",az önző",
                    ",a jámbor",
                    ",a féktelen",
                    ",az ostoba",
                    ",a kardnyelő",
                    ",a komor",
                    ",a vellám",
                    ",a golyók ura",
                    ",a hálátlan",
                    ",a szentségtelen",
                    ",a tisztátalan",
                    ",a szent",
                    ",az undorító",
                    ",a hercegnő",
                    ",az iszonyat",
                    ",az ítélethozó",
                    ",az irgalmatlan",
                    ",a pusztító",
                    ",a rettenthetetlen"
];

function generateName(){
    let fullName = FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)];
    fullName += NICKNAMES[Math.floor(Math.random() * NICKNAMES.length)];
    return fullName; 
}

module.exports = generateName;